import json
from pathlib import Path


def run(job_id: str, project_root: Path) -> dict:
    """
    Returns {"ai_gaps": [...], "prop_library_gaps": [...]}

    ai_gaps         — missing clips where needs_prop_library is False.
                      These are auto-filled by generate_ai_footage.py.
    prop_library_gaps — missing clips requiring a self-filmed desk prop.
                      These halt the pipeline — user must film and drop in footage/<job-id>/gaps/.
    """
    script_file = project_root / "scripts" / job_id / "script.json"
    if not script_file.exists():
        raise FileNotFoundError(f"Script not found: {script_file}. Run generate_script first.")
    try:
        script = json.loads(script_file.read_text())
    except (json.JSONDecodeError, OSError) as e:
        raise RuntimeError(f"Could not read script for job {job_id}: {e}") from e

    footage_dir = project_root / "footage" / job_id

    ai_gaps = []
    prop_library_gaps = []

    for i, sentence in enumerate(script["sentences"]):
        stock_clip = footage_dir / f"clip_{i:02d}.mp4"
        gap_clip = footage_dir / "gaps" / f"clip_{i:02d}.mp4"
        if stock_clip.exists() or gap_clip.exists():
            continue

        runway_prompt = (
            sentence.get("runway_prompt")
            or f"Close-up of {sentence['pexels_query']}, cinematic, 4K, no people"
        )
        gap = {
            "sentence_idx": i,
            "text": sentence["text"],
            "overlay": sentence["overlay"],
            "runway_prompt": runway_prompt,
            "needs_prop_library": sentence.get("needs_prop_library", False),
            "prop_description": sentence.get("prop_description"),
        }
        if sentence.get("needs_prop_library"):
            prop_library_gaps.append(gap)
        else:
            ai_gaps.append(gap)

    out_dir = project_root / "assets" / job_id
    out_dir.mkdir(parents=True, exist_ok=True)
    gaps_file = out_dir / "footage-gaps.md"

    total = len(ai_gaps) + len(prop_library_gaps)
    if total == 0:
        gaps_file.write_text("No footage gaps — all clips found.\n")
        print("✅ No footage gaps")
        return {"ai_gaps": [], "prop_library_gaps": []}

    lines = [f"# Footage Gaps — {job_id}\n"]

    if ai_gaps:
        lines += [
            f"## AI Gaps ({len(ai_gaps)}) — auto-generated by pipeline\n",
            "These will be filled automatically via the Runway API.\n",
        ]
        for g in ai_gaps:
            lines += [
                f"### Gap #{g['sentence_idx']:02d} — overlay: {g['overlay']}",
                f"**Script:** \"{g['text']}\"",
                f"**Runway Prompt:** `{g['runway_prompt']}`\n",
            ]

    if prop_library_gaps:
        lines += [
            f"## Prop Library Gaps ({len(prop_library_gaps)}) — MANUAL FILMING REQUIRED\n",
            "These clips require a self-filmed desk prop close-up.",
            f"Film the prop and save each as `clip_XX.mp4` in `footage/{job_id}/gaps/`",
            f"Then re-run: `python pipeline.py --job {job_id}`\n",
        ]
        for g in prop_library_gaps:
            lines += [
                f"### Gap #{g['sentence_idx']:02d} — overlay: {g['overlay']}",
                f"**Script:** \"{g['text']}\"",
                f"**Prop needed:** {g['prop_description'] or 'desk prop close-up'}\n",
            ]

    gaps_file.write_text("\n".join(lines))
    if ai_gaps:
        print(f"🤖 {len(ai_gaps)} AI gaps — will auto-generate via Runway API")
    if prop_library_gaps:
        print(f"⚠️  {len(prop_library_gaps)} prop library gaps → manual filming required")
        print(f"   See: {gaps_file}")
    return {"ai_gaps": ai_gaps, "prop_library_gaps": prop_library_gaps}


if __name__ == "__main__":
    import sys
    project_root = Path(__file__).parent.parent
    run(sys.argv[1], project_root)
