"""
package_assets.py — Bundle all pre-edit assets into assets/<job_id>/ for CapCut assembly.

Usage:
    python tools/package_assets.py <job_id>

Inputs (must exist before running):
    scripts/<job_id>/script.json   — generated by generate_script.py
    footage/<job_id>/clip_NN.mp4   — sourced by search_footage.py / generate_ai_footage.py
    footage/<job_id>/gaps/clip_NN.mp4  — gap fills (take priority over stock clips)
    voiceover/<job_id>/voiceover.mp3   — generated by generate_voiceover.py
    assets/<job_id>/music.mp3          — selected by select_music.py

Outputs (written to assets/<job_id>/):
    NN_clip.mp4      numbered clips (gap fills preferred over stock)
    voiceover.mp3    copy of voiceover
    thumbnail.jpg    first frame of clip 01 (via ffmpeg)
    script.txt       timestamped script lines for editor reference
    overlays.txt     timestamps + overlay text + color pop hints
    music-timing.txt EQ dip/swell markers for CapCut
    loop.txt         opening/closing shot descriptions for seamless loop
"""

import json
import shutil
import subprocess
from pathlib import Path


def _extract_thumbnail(clip_path: Path, out_path: Path) -> bool:
    result = subprocess.run(
        ["ffmpeg", "-i", str(clip_path), "-vframes", "1", "-q:v", "2", "-y", str(out_path)],
        capture_output=True,
    )
    return result.returncode == 0


def run(job_id: str, project_root: Path) -> Path:
    script_file = project_root / "scripts" / job_id / "script.json"
    if not script_file.exists():
        raise FileNotFoundError(f"Script not found: {script_file}. Run generate_script first.")
    try:
        script = json.loads(script_file.read_text())
    except (json.JSONDecodeError, OSError) as e:
        raise RuntimeError(f"Could not read script for job {job_id}: {e}") from e

    sentences = script["sentences"]
    footage_dir = project_root / "footage" / job_id
    voiceover_src = project_root / "voiceover" / job_id / "voiceover.mp3"

    out_dir = project_root / "assets" / job_id
    out_dir.mkdir(parents=True, exist_ok=True)

    # Copy clips — gap-filled clips take priority over stock
    for i, _ in enumerate(sentences):
        gap_clip = footage_dir / "gaps" / f"clip_{i:02d}.mp4"
        stock_clip = footage_dir / f"clip_{i:02d}.mp4"
        src = gap_clip if gap_clip.exists() else stock_clip
        if src.exists():
            shutil.copy2(src, out_dir / f"{i+1:02d}_clip.mp4")

    # Extract thumbnail from first clip
    first_clip = out_dir / "01_clip.mp4"
    if first_clip.exists():
        try:
            success = _extract_thumbnail(first_clip, out_dir / "thumbnail.jpg")
        except FileNotFoundError:
            success = False
        if success:
            print("✅ thumbnail.jpg extracted from clip 01 (ready for YouTube upload)")
        else:
            print("⚠️  Thumbnail extraction failed — save first frame of clip 01 manually as thumbnail.jpg")

    # Copy voiceover
    if voiceover_src.exists():
        shutil.copy2(voiceover_src, out_dir / "voiceover.mp3")
    else:
        print(f"Warning: voiceover not found at {voiceover_src}, skipping")

    # script.txt — timestamped lines for reference while editing
    script_lines = [f"=== {job_id} ===\n"]
    for s in sentences:
        script_lines.append(f"[{s['timestamp_approx']}] {s['text']}")
    (out_dir / "script.txt").write_text("\n".join(script_lines))

    # overlays.txt — timestamp + keyword + color pop words for each sentence
    overlay_lines = []
    for s in sentences:
        pops = " ".join(s.get("color_pop_words", []))
        pop_note = f"  (color pop: {pops})" if pops else ""
        overlay_lines.append(f"[{s['timestamp_approx']}] {s['overlay']}{pop_note}")
    (out_dir / "overlays.txt").write_text("\n".join(overlay_lines))

    # music-timing.txt — EQ markers for CapCut assembly
    music_timing = script.get("music_timing", {})
    if music_timing:
        timing_lines = [
            f"Music EQ markers for {job_id}",
            f"",
            f"DIP:   [{music_timing.get('dip_timestamp_approx', '?')}] sentence {music_timing.get('dip_at_sentence_index', '?')}",
            f"       {music_timing.get('dip_instruction', '')}",
            f"",
            f"SWELL: [{music_timing.get('swell_timestamp_approx', '?')}] sentence {music_timing.get('swell_at_sentence_index', '?')}",
            f"       {music_timing.get('swell_instruction', '')}",
        ]
        (out_dir / "music-timing.txt").write_text("\n".join(timing_lines))

    # loop.txt — opening and closing shot descriptions for seamless loop
    loop = script.get("loop", {})
    if loop:
        loop_lines = [
            f"Seamless Loop Instructions — {job_id}",
            f"",
            f"OPENING SHOT (clip 01): {loop.get('opening_shot_description', '')}",
            f"CLOSING SHOT (last clip): {loop.get('closing_shot_description', '')}",
            f"",
            f"Loop confirmed: {loop.get('loop_match_confirmed', False)}",
            f"",
            f"RULE: First frame and last frame must match exactly. Zero exceptions.",
        ]
        (out_dir / "loop.txt").write_text("\n".join(loop_lines))

    clips_count = len(list(out_dir.glob("*_clip.mp4")))
    has_voiceover = (out_dir / "voiceover.mp3").exists()
    has_music = (out_dir / "music.mp3").exists()
    footage_gaps_file = out_dir / "footage-gaps.md"
    has_gaps = footage_gaps_file.exists() and "No footage gaps" not in footage_gaps_file.read_text()

    has_loop = (out_dir / "loop.txt").exists()
    has_timing = (out_dir / "music-timing.txt").exists()

    print(f"""
✅ Asset bundle ready: assets/{job_id}/

📋 EDIT CHECKLIST — open this folder in CapCut:
  {"✅" if has_voiceover else "❌"} voiceover.mp3
  {"✅" if has_music else "⚠️ "} music.mp3  (add a track if missing)
  {clips_count} clips numbered for assembly
  ✅ script.txt  (timestamped reference)
  ✅ overlays.txt  (timestamps + color pop words)
  {"✅" if has_timing else "⚠️ "} music-timing.txt  (EQ dip/swell markers)
  {"✅" if has_loop else "⚠️ "} loop.txt  (opening/closing shot descriptions)
  {"⚠️  footage-gaps.md has unresolved gaps" if has_gaps else "✅ no footage gaps"}

⚠️  SEAMLESS LOOP: Opening clip and closing clip must match — read loop.txt.
⚠️  THUMBNAIL: First clip first frame must show the object in clear focus.
    This becomes the YouTube Shorts thumbnail.

Next: edit in CapCut → export to output/{job_id}/final.mp4
Then: python publish.py --job {job_id}
""")
    return out_dir


if __name__ == "__main__":
    import sys
    project_root = Path(__file__).parent.parent
    run(sys.argv[1], project_root)
